# Generated by Django 3.1.5 on 2021-02-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210211_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='auctions.Comments'),
        ),
    ]
