# Generated by Django 3.1.5 on 2021-02-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210211_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='description',
        ),
    ]
