# Generated by Django 3.1.5 on 2021-02-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listings_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('Fiction', 'FICTION'), ('Children', 'CHILDREN'), ('Fantasy', 'FANTASY'), ('NonFiction', 'NON-FICTION'), ('Sci-Fi', 'SCI-FI'), ('Young Adult', 'YOUNG ADULT'), ('Mystery', 'MYSTERY'), ('Historical Fiction', 'HISTORICAL FICTION'), ('Classics', 'CLASSICS'), ('Comics', 'COMICS')], default='', max_length=30),
        ),
    ]
