# Generated by Django 3.1.5 on 2021-02-15 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210215_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='lister',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listers', to=settings.AUTH_USER_MODEL),
        ),
    ]
